//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBPOS_Reports.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>{\"Key\":\"ND_1\",\"Name\":\"Αναφορά Αποδείξεων\",\"ClassName\":\"Receipts\"}</string>" +
            "\r\n  <string>{\"Key\":\"ND_2\",\"Name\":\"Πωλήσεις ανά Σερβιτόρο\",\"ClassName\":\"SalesPerW" +
            "aiter\"}</string>\r\n  <string>{\"Key\":\"ND_3\",\"Name\":\"Ημερολόγιο Πωλήσεων\",\"ClassNam" +
            "e\":\"SalesDiary\"}</string>\r\n  <string>{\"Key\":\"NF_1\",\"Name\":\"Αρχείο Ειδών\",\"ClassN" +
            "ame\":\"ProductFilesPivot\"}</string>\r\n  <string>{\"Key\":\"NF_2\",\"Name\":\"Προϊόντα ανά" +
            " Σελίδα\",\"ClassName\":\"PageButton\"}</string>\r\n  <string>{\"Key\":\"NF_3\",\"Name\":\"Προ" +
            "ϊόντα ανά Σελίδα και POS\",\"ClassName\":\"PageButtonPerPos\"}</string>\r\n  <string>{\"" +
            "Key\":\"NSB1\",\"Name\":\"Best Seller Εσόδων ανά POS\",\"ClassName\":\"BestSellerRevenuePe" +
            "rPos\"}</string>\r\n  <string>{\"Key\":\"NSB2\",\"Name\":\"Best Seller ανά Αξία\",\"ClassNam" +
            "e\":\"BestSellerRevenue\"}</string>\r\n  <string>{\"Key\":\"NSB3\",\"Name\":\"Best Seller αν" +
            "ά Ποσότητα\",\"ClassName\":\"BestSellerQty\"}</string>\r\n  <string>{\"Key\":\"NSB4\",\"Name" +
            "\":\"Best Seller Ποσότητας ανά Κατηγορία Είδους\",\"ClassName\":\"BestSellerQtyGrpPC\"}" +
            "</string>\r\n  <string>{\"Key\":\"NSR1\",\"Name\":\"Πωλήσεις Complimentary vs Room\",\"Clas" +
            "sName\":\"CoplimenatryVsRoom\"}</string>\r\n  <string>{\"Key\":\"NSR2\",\"Name\":\"Πωλήσεις " +
            "Complimentary vs Room Area\",\"ClassName\":\"CoplimenatryVsRoomArea\"}</string>\r\n  <s" +
            "tring>{\"Key\":\"NSR3\",\"Name\":\"Πωλήσεις ανά Δωμάτιο Συνοπτικά\",\"ClassName\":\"SalesPe" +
            "rRoomTotal\"}</string>\r\n  <string>{\"Key\":\"NSO1\",\"Name\":\"Πωλήσεις Ειδών ανά Χειρισ" +
            "τή - Συνοπτικά\",\"ClassName\":\"SalesPerStaffTotal\"}</string>\r\n  <string>{\"Key\":\"NS" +
            "O2\",\"Name\":\"Πωλήσεις Ειδών ανά Χειριστή και POS - Συνοπτικά\",\"ClassName\":\"SalesP" +
            "erStaffAndPosTotal\"}</string>\r\n  <string>{\"Key\":\"NSO3\",\"Name\":\"Πωλήσεις ανά Χειρ" +
            "ιστή και Τρόπο Πληρωμής - Συνοπτικά\",\"ClassName\":\"SalesPerPaymentTotal2\"}</strin" +
            "g>\r\n  <string>{\"Key\":\"NSO4\",\"Name\":\"Πωλήσεις Ειδών ανά Χειριστή - Αναλυτικά\",\"Cl" +
            "assName\":\"SalesPerStaffAnalytical\"}</string>\r\n  <string>{\"Key\":\"NSO5\",\"Name\":\"Πω" +
            "λήσεις Ειδών ανά Χειριστή και POS - Αναλυτικά\",\"ClassName\":\"SalesPerStaffAndPosA" +
            "nalytical\"}</string>\r\n  <string>{\"Key\":\"NSO6\",\"Name\":\"Πωλήσεις Ειδών ανά Χειριστ" +
            "ή POS και Τιμοκατάλογο - Αναλυτικά\",\"ClassName\":\"SalesPerStaffPosPricelistAnalyt" +
            "ical\"}</string>\r\n  <string>{\"Key\":\"NSO7\",\"Name\":\"Πωλήσεις ανά Χειριστή, Τιμοκατά" +
            "λογο και Κατηγορία - Συνοπτικά\",\"ClassName\":\"SalesPerStaffPricelistCategory2\"}</" +
            "string>\r\n  <string>{\"Key\":\"NSO8\",\"Name\":\"Πωλήσεις ανά Χειριστή, Τιμοκατάλογο και" +
            " Κατηγορία Προϊόντων - Συνοπτικά\",\"ClassName\":\"SalesPerStaffPricelistCategory3\"}" +
            "</string>\r\n  <string>{\"Key\":\"NSO9\",\"Name\":\"Δελτία Παραγγελίας ανά Χειριστή - Ανα" +
            "λυτικά\",\"ClassName\":\"OrdersPerStaffAnalytical\"}</string>\r\n  <string>{\"Key\":\"NSP1" +
            "\",\"Name\":\"Πωλήσεις ανά Τιμοκατάλογο και Άτομα - Συνοπτικά\",\"ClassName\":\"SalesPer" +
            "PricelistCoverTotal2\"}</string>\r\n  <string>{\"Key\":\"NSP2\",\"Name\":\"Πωλήσεις Ειδών " +
            "ανά Τιμοκατάλογο\",\"ClassName\":\"SalesPerPricelist\"}</string>\r\n  <string>{\"Key\":\"N" +
            "SP3\",\"Name\":\"Πωλήσεις Ειδών ανά Τιμοκατάλογο και POS\",\"ClassName\":\"SalesPerPrice" +
            "listAndPos\"}</string>\r\n  <string>{\"Key\":\"NSP4\",\"Name\":\"Πωλήσεις Ειδών ανά Τιμοκα" +
            "τάλογο POS και Κατηγορία\",\"ClassName\":\"SalesPerPricelistPosCategory\"}</string>\r\n" +
            "  <string>{\"Key\":\"NSC1\",\"Name\":\"Πωλήσεις Ειδών ανά Κατηγορία\",\"ClassName\":\"Sales" +
            "PerCategory\"}</string>\r\n  <string>{\"Key\":\"NSC2\",\"Name\":\"Πωλήσεις Ειδών ανά Κατηγ" +
            "ορία και POS\",\"ClassName\":\"SalesPerCategoryAndPos\"}</string>\r\n  <string>{\"Key\":\"" +
            "NSC3\",\"Name\":\"Πωλήσεις Ειδών ανά Κατηγορία και POS - Συνοπτικά\",\"ClassName\":\"Sal" +
            "esPerCategoryAndPosTotal\"}</string>\r\n  <string>{\"Key\":\"NSF1\",\"Name\":\"Πωλήσεις αν" +
            "ά Είδος (flat)\",\"ClassName\":\"SalesPerProductFlat\"}</string>\r\n  <string>{\"Key\":\"N" +
            "SF2\",\"Name\":\"Πωλήσεις ανά Τιμοκατάλογο, Είδος και ΦΠΑ (flat)\",\"ClassName\":\"Sales" +
            "PerPricelistCodeVat_Flat\"}</string>\r\n  <string>{\"Key\":\"NS_1\",\"Name\":\"Κόστος Πωλη" +
            "θέντων\",\"ClassName\":\"SalesCostAL\"}</string>\r\n  <string>{\"Key\":\"NS_2\",\"Name\":\"Καθ" +
            "αρές Αξίες Πωλήσεων\",\"ClassName\":\"SalesNetAmount2\"}</string>\r\n  <string>{\"Key\":\"" +
            "NS_3\",\"Name\":\"Ωριαίες Πωλήσεις Ειδών\",\"ClassName\":\"HourlyProductSales\"}</string>" +
            "\r\n  <string>{\"Key\":\"NS_4\",\"Name\":\"Food and Beverage Statistics\",\"ClassName\":\"FnB" +
            "_Statistics\"}</string>\r\n  <string>{\"Key\":\"NS_5\",\"Name\":\"Πωλήσεις ανά Τραπέζι - Α" +
            "ναλυτικά\",\"ClassName\":\"SalesPerCategoryAndPosAndRegionTables\"}</string>\r\n  <stri" +
            "ng>{\"Key\":\"NS_6\",\"Name\":\"Πωλήσεις ανά Buzzer - Αναλυτικά\",\"ClassName\":\"SalesPerB" +
            "uzzerAnalytical\"}</string>\r\n  <string>{\"Key\":\"NP_1\",\"Name\":\"Εκτύπωση Κλεισίματος" +
            "\",\"ClassName\":\"EndOfDay\"}</string>\r\n  <string>{\"Key\":\"NP_2\",\"Name\":\"Εκτύπωση Κλε" +
            "ισίματος Ανά Δωμάτιο\",\"ClassName\":\"EndOfDayPerRoom\"}</string>\r\n  <string>{\"Key\":" +
            "\"OD_1\",\"Name\":\"Αναφορά Αποδείξεων\",\"ClassName\":\"ReceiptsOldDB\"}</string>\r\n  <str" +
            "ing>{\"Key\":\"OD_2\",\"Name\":\"Πωλήσεις ανά Σερβιτόρο\",\"ClassName\":\"SalesPerWaiterOld" +
            "DB\"}</string>\r\n  <string>{\"Key\":\"OD_3\",\"Name\":\"Πωλήσεις ανά Τραπέζι\",\"ClassName\"" +
            ":\"RevenuePerTableOldDB\"}</string>\r\n  <string>{\"Key\":\"OF_1\",\"Name\":\"Αρχείο Ειδών\"" +
            ",\"ClassName\":\"ProductFilesPivot\"}</string>\r\n  <string>{\"Key\":\"OF_2\",\"Name\":\"Προϊ" +
            "όντα ανά Σελίδα\",\"ClassName\":\"PageButton\"}</string>\r\n  <string>{\"Key\":\"OF_3\",\"Na" +
            "me\":\"Προϊόντα ανά Σελίδα και POS\",\"ClassName\":\"PageButtonPerPos\"}</string>\r\n  <s" +
            "tring>{\"Key\":\"OSB1\",\"Name\":\"Best Seller Εσόδων ανά POS\",\"ClassName\":\"BestSellerR" +
            "evenuePerPosOldDB\"}</string>\r\n  <string>{\"Key\":\"OSB2\",\"Name\":\"Best Seller ανά Αξ" +
            "ία\",\"ClassName\":\"BestSellerRevenue2OldDB\"}</string>\r\n  <string>{\"Key\":\"OSB3\",\"Na" +
            "me\":\"Best Seller ανά Ποσότητα\",\"ClassName\":\"BestSellerQtyOldDB\"}</string>\r\n  <st" +
            "ring>{\"Key\":\"OS_1\",\"Name\":\"Πωλήσεις Ειδών ανά Χειριστή Συνοπτικά\",\"ClassName\":\"S" +
            "alesPerStaffTotalOldDB\"}</string>\r\n  <string>{\"Key\":\"OS_2\",\"Name\":\"Πωλήσεις Ειδώ" +
            "ν ανά Χειριστή Αναλυτικά\",\"ClassName\":\"SalesPerStaffAnalyticalOldDB\"}</string>\r\n" +
            "  <string>{\"Key\":\"OS_3\",\"Name\":\"Πωλήσεις Ειδών ανά Τιμοκατάλογο\",\"ClassName\":\"Sa" +
            "lesPerPricelistOldDB\"}</string>\r\n  <string>{\"Key\":\"OS_4\",\"Name\":\"Πωλήσεις Ειδών " +
            "ανά Κατηγορία\",\"ClassName\":\"SalesPerCategoryOldDB\"}</string>\r\n  <string>{\"Key\":\"" +
            "OS_5\",\"Name\":\"Πωλήσεις Ειδών ανά Κατηγορία και POS\",\"ClassName\":\"SalesPerCategor" +
            "yAndPosOldDB\"}</string>\r\n  <string>{\"Key\":\"OS_6\",\"Name\":\"Κόστος Πωληθέντων\",\"Cla" +
            "ssName\":\"SalesCostOldDB\"}</string>\r\n  <string>{\"Key\":\"OS_7\",\"Name\":\"Ωριαίες Πωλή" +
            "σεις ανά Τύπο Παραστατικού Συνοπτικά\",\"ClassName\":\"HourlySalesPerInvoiceTypeTota" +
            "l_OldDB\"}</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Reports {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Reports"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Actions</string>
  <string>Categories</string>
  <string>Department</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Tables {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Tables"]));
            }
        }
    }
}
