//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBPOS_Reports.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EFReportEntity
    {
        public int Id { get; set; }
        public string Url { get; set; }
        public byte[] Layout { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
        public string ReportName { get; set; }
        public string Menu { get; set; }
        public string Submenu { get; set; }
    }
}
